# MadLib.py
adjective = input("Please enter an adjective: ")
noun = input("Please enter a noun: ")
verb = input("Please enter a verb ending in -ed: ")
adverb1 = input("Please enter an adverb: ")
noun1 = input("Please enter a noun: ")
verb1 = input("Please enter a verb ending in -ing: ")
print("Your MadLib:")
print("The", adjective, noun, verb, "over the lazy brown dog.")
print("She saw the", adverb1, noun1, verb1, "off the building.")
